const START_POSITION = { x: 1000, y: 1000 };
const BULLET_LIFETIME = 60 * 12;
const ASSUMED_FPS = 60;
const LEVEL_DURATION = 20;
const LEVEL_DURATION_FRAMES = LEVEL_DURATION * ASSUMED_FPS;
const LEVEL_TRANSITION_FRAMES = 90;
const SHOP_DURATION_FRAMES = 15 * ASSUMED_FPS;
const LASER_WARNING_TIME = 1 * ASSUMED_FPS;
const LASER_FLASH_TIME = 8;
const PREDICTIVE_LASER_BURST_COUNT = 5;
const PREDICTIVE_LASER_GAP_FRAMES = 18;
const PLAYER_HISTORY_FRAMES = ASSUMED_FPS;
const FLARE_LIFE = 60;
const TRACKING_ONSCREEN_LIFETIME_BONUS = 6 * ASSUMED_FPS;
const MIN_VIEW_SCALE = 0.68;
const VIEW_SCALE_PER_SPEED = 0.08;
const DASH_COOLDOWN_START = 240;
const DASH_COOLDOWN_STEP = 30;
const DASH_COOLDOWN_MIN = 45;
const SHIELD_COOLDOWN_START = 420;
const SHIELD_COOLDOWN_STEP = 60;
const SHIELD_COOLDOWN_MIN = 90;
const SHIELD_DURATION_START = 60;
const SHIELD_DURATION_STEP = 60;
const SHIELD_DURATION_MAX = 300;
const FLARE_COOLDOWN_START = 300;
const FLARE_COOLDOWN_STEP = 35;
const FLARE_COOLDOWN_MIN = 70;
const SPEED_UPGRADE_AMOUNT = 0.4;
const DASH_DISTANCE_START = 50;
const DASH_DISTANCE_STEP = 12;
const FLARE_RADIAL_SHOTS_STEP = 4;
const PLAYER_MAX_HP = 3;
const PLAYER_HIT_INVULNERABILITY_FRAMES = 36;
const SHOP_HEAL_AMOUNT = 0.5;
const LASER_SHIELD_DAMAGE = 5;
const CLOSE_DODGE_RADIUS = 20;
const CLOSE_DODGE_BONUS = 0.1;
const SCORE_MULTIPLIER_VALUE = 2;
const SCORE_MULTIPLIER_DURATION_FRAMES = 3 * ASSUMED_FPS;
const CHECKPOINT_INTERVAL = 5;
const BOSS_LEVEL_INTERVAL = 10;
const BOSS_BACKGROUND_SPAWN_FACTOR = 5;
const GAME_MODES = {
    CLASSIC: "classic",
    CHECKPOINT: "checkpoint",
    TESTING: "testing"
};
const TESTING_FIELDS = [
    { key: "startLevel", label: "Start Level", min: 1 },
    { key: "dashTier", label: "Dash Tier", min: 0 },
    { key: "shieldTier", label: "Shield Tier", min: 0 },
    { key: "flareTier", label: "Flare Tier", min: 0 },
    { key: "speedUps", label: "Speed Ups", min: 0 }
];
const SAVE_STATUS_DURATION_FRAMES = 3 * ASSUMED_FPS;
const API_ENDPOINTS = {
    BOOTSTRAP: "/api/bootstrap",
    HIGH_SCORE: "/api/high-score",
    SAVED_GAME: "/api/saved-game"
};
